logging:
  file:
    path: /var/rina_log
  level:
    com:
      rina: error

#生产模式下禁用swagger-ui
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

#生产模式下禁用devtools
spring:
  profiles:
    - prod
  devtools:
    restart:
      enabled: false