server:
  port: 8080

logging:
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
              %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 10

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-wait: 30000
        max-active: 10
        max-idle: 10
        min-idle: 0
    connect-timeout: 3000
    timeout: 3000
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:prod}

mybatis:
  type-aliases-package: com.rina.domain
  mapper-locations: classpath:com/rina/mapper/*.xml
  configuration:
    # 开启分步查询的延迟加载
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

rina:
  jwt:
    # token所对应header名
    header: ${HEADER:Authorization}
    # token过期时间
    token-expire-time: ${TOKEN_EXPIRE_TIME:60*1000}
    # 缓存方式，此处如有需要可改为guava
    cache-type: ${CACHE_TYPE:redis}
  async-pool:
    # 核心线程数
    core-pool-size: ${CORE_POOL_SIZE:2}
    # 最大线程数
    max-pool-size: ${MAX_POOL_SIZE:5}
    # 队列大小
    queue-capacity: ${QUEUE_CAPACITY:10}
    # 线程最大空闲时间
    keep-alive-seconds: ${KEEP_ALIVE_SECONDS:6}